name: AMOLED Waterfox Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y wget unzip jq zipalign apksigner openjdk-17-jdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        unzip tools.zip -d cmdline
        mkdir -p $HOME/android-sdk/cmdline-tools
        mv cmdline $HOME/android-sdk/cmdline-tools/latest
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        yes | sdkmanager --licenses || true
        sdkmanager "build-tools;34.0.0"

    - name: Get Waterfox version
      run: |
        echo "BUILD_VERSION=$(curl -s https://api.github.com/repos/BrowserWorks/waterfox-android/releases/latest | jq -r .tag_name)" >> $GITHUB_ENV

    - name: Check for existing release
      id: check
      run: |
        if gh release view "$BUILD_VERSION" &>/dev/null; then
          echo "Release $BUILD_VERSION already exists."
          exit 0
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Patch armeabi-v7a
      run: |
        bash build.sh armeabi-v7a
        mv patched_signed.apk waterfox-${{ env.BUILD_VERSION }}-armeabi-AMOLED.apk

    - name: Patch arm64-v8a
      run: |
        bash build.sh arm64-v8a
        mv patched_signed.apk waterfox-${{ env.BUILD_VERSION }}-arm64-AMOLED.apk

    - name: Setup keystore
      run: echo "${{ secrets.KEYSTORE }}" | base64 -d > keystore.jks

    - name: Sign APKs
      run: |
        apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSPHRASE }} waterfox-${{ env.BUILD_VERSION }}-armeabi-AMOLED.apk
        apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSPHRASE }} waterfox-${{ env.BUILD_VERSION }}-arm64-AMOLED.apk

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.BUILD_VERSION }}
        name: AMOLED Waterfox ${{ env.BUILD_VERSION }}
        body: |
          AMOLED-patched builds of Waterfox Android.
        files: |
          waterfox-${{ env.BUILD_VERSION }}-armeabi-AMOLED.apk
          waterfox-${{ env.BUILD_VERSION }}-arm64-AMOLED.apk
