name: Build and Release AMOLED Waterfox

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up signing key
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > keystore.jks
          echo "STORE_FILE=keystore.jks" >> $GITHUB_ENV
          echo "STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Build armeabi-v7a
        run: ./build.sh armeabi-v7a

      - name: Sign armeabi-v7a
        run: |
          apksigner sign \
            --ks $STORE_FILE \
            --ks-pass pass:$STORE_PASSWORD \
            --key-pass pass:$KEY_PASSWORD \
            --ks-key-alias $KEY_ALIAS \
            --out armeabi-v7a-signed.apk \
            patched_signed.apk
        shell: bash

      - name: Upload armeabi-v7a
        uses: actions/upload-artifact@v4
        with:
          name: waterfox-amoled-armeabi-v7a
          path: armeabi-v7a-signed.apk

      - name: Build arm64-v8a
        run: ./build.sh arm64-v8a

      - name: Sign arm64-v8a
        run: |
          apksigner sign \
            --ks $STORE_FILE \
            --ks-pass pass:$STORE_PASSWORD \
            --key-pass pass:$KEY_PASSWORD \
            --ks-key-alias $KEY_ALIAS \
            --out arm64-v8a-signed.apk \
            patched_signed.apk
        shell: bash

      - name: Upload arm64-v8a
        uses: actions/upload-artifact@v4
        with:
          name: waterfox-amoled-arm64-v8a
          path: arm64-v8a-signed.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            armeabi-v7a-signed.apk
            arm64-v8a-signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
