name: build-and-release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android build tools (zipalign, apksigner)
        run: |
          sudo apt update
          sudo apt install -y zipalign lib32stdc++6

          mkdir -p "$HOME/android"
          cd "$HOME/android"

          curl -O https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-*.zip -d cmdline-tools
          mkdir -p $HOME/android/sdk/cmdline-tools/latest
          mv cmdline-tools/* $HOME/android/sdk/cmdline-tools/latest

          yes | $HOME/android/sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android/sdk "build-tools;34.0.0"

          echo "$HOME/android/sdk/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Download armeabi-v7a APK
        run: |
          curl -L -o latest-armeabi.apk https://github.com/BrowserWorks/waterfox-android/releases/download/1.1.1/waterfox-1.1.1-armeabi-v7a-release.apk

      - name: Patch armeabi-v7a
        run: |
          chmod +x ./build.sh
          ./build.sh latest-armeabi.apk armeabi

      - name: Sign armeabi-v7a APK
        run: |
          FILE=$(ls waterfox*-armeabi-v7a-AMOLED.apk)
          apksigner sign --ks debug.keystore --ks-pass pass:android --key-pass pass:android --out signed-armeabi.apk "$FILE"

      - name: Download arm64-v8a APK
        run: |
          curl -L -o latest-arm64.apk https://github.com/BrowserWorks/waterfox-android/releases/download/1.1.1/waterfox-1.1.1-arm64-v8a-release.apk

      - name: Patch arm64-v8a
        run: |
          chmod +x ./build.sh
          ./build.sh latest-arm64.apk arm64

      - name: Sign arm64-v8a APK
        run: |
          FILE=$(ls waterfox*-arm64-v8a-AMOLED.apk)
          apksigner sign --ks debug.keystore --ks-pass pass:android --key-pass pass:android --out signed-arm64.apk "$FILE"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Waterfox AMOLED ${{ github.ref_name }}
          body: |
            AMOLED build of Waterfox Android based on upstream release ${{ github.ref_name }}.
            Credits to BrowserWorks for the original APKs.
          files: |
            signed-armeabi.apk
            signed-arm64.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
