name: Build and Release AMOLED Waterfox

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget unzip zip openjdk-17-jdk jq
        mkdir -p "$HOME/android-sdk/cmdline-tools"
        cd "$HOME/android-sdk/cmdline-tools"
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses
        sdkmanager "build-tools;34.0.0"
        echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

    - name: Set up debug.keystore
      run: |
        echo "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 -d > debug.keystore

    - name: Fetch latest release tag
      run: |
        wget -q https://api.github.com/repos/BrowserWorks/waterfox-android/releases/latest -O release.json
        TAG=$(jq -r '.tag_name' release.json)
        echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV

    - name: Download official APKs
      run: |
        mkdir -p apks
        wget -O apks/armeabi.apk "https://github.com/BrowserWorks/waterfox-android/releases/download/${{ env.RELEASE_TAG }}/waterfox-${{ env.RELEASE_TAG }}-armeabi-v7a-release.apk"
        wget -O apks/arm64.apk "https://github.com/BrowserWorks/waterfox-android/releases/download/${{ env.RELEASE_TAG }}/waterfox-${{ env.RELEASE_TAG }}-arm64-v8a-release.apk"

    - name: Patch armeabi-v7a
      run: |
        bash build.sh apks/armeabi.apk armeabi-v7a

    - name: Patch arm64-v8a
      run: |
        bash build.sh apks/arm64.apk arm64-v8a

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: AMOLED Waterfox ${{ env.RELEASE_TAG }}
        body: |
          Auto-generated AMOLED-patched builds of Waterfox Android.
        files: |
          output/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
