name: AMOLED Waterfox Build

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget jq zipalign apksigner default-jdk

      - name: Fetch latest Waterfox release
        id: fetch
        run: |
          TAG=$(curl -s https://api.github.com/repos/BrowserWorks/waterfox-android/releases/latest | jq -r .tag_name)
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Check if release already exists
        run: |
          if gh release view "amoled-${{ steps.fetch.outputs.tag }}" &>/dev/null; then
            echo "Already released."
            exit 0
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Patch armeabi-v7a
        run: |
          chmod +x ./build.sh
          ./build.sh armeabi-v7a
          mv patched_signed.apk waterfox-${{ steps.fetch.outputs.tag }}-armeabi-v7a-AMOLED.apk

      - name: Patch arm64-v8a
        run: |
          ./build.sh arm64-v8a
          mv patched_signed.apk waterfox-${{ steps.fetch.outputs.tag }}-arm64-v8a-AMOLED.apk

      - name: Generate debug keystore if missing
        run: |
          if [ ! -f debug.keystore ]; then
            keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android \
              -dname "CN=Android Debug,O=Android,C=US" -keyalg RSA -keysize 2048 -validity 10000
          fi

      - name: Sign APKs
        run: |
          apksigner sign --ks debug.keystore --ks-pass pass:android waterfox-${{ steps.fetch.outputs.tag }}-armeabi-v7a-AMOLED.apk
          apksigner sign --ks debug.keystore --ks-pass pass:android waterfox-${{ steps.fetch.outputs.tag }}-arm64-v8a-AMOLED.apk

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: amoled-${{ steps.fetch.outputs.tag }}
          name: AMOLED Waterfox ${{ steps.fetch.outputs.tag }}
          body: |
            ✅ Auto-generated AMOLED-patched Waterfox Android builds.
          files: |
            waterfox-${{ steps.fetch.outputs.tag }}-armeabi-v7a-AMOLED.apk
            waterfox-${{ steps.fetch.outputs.tag }}-arm64-v8a-AMOLED.apk
