name: AMOLED Waterfox Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget jq zipalign apksigner apktool

      - name: Get latest Waterfox release version
        id: get_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/BrowserWorks/waterfox-android/releases/latest | jq -r .tag_name)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      # FIXED: Remove existing release if present instead of failing
      - name: Remove existing release if exists
        run: |
          if gh release view "amoled-${{ env.VERSION }}" &>/dev/null; then
            gh release delete "amoled-${{ env.VERSION }}" --yes
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Patch armeabi-v7a
        run: |
          chmod +x ./build.sh
          ./build.sh armeabi-v7a
          mv patched_signed.apk waterfox-${{ env.VERSION }}-armeabi-v7a-AMOLED.apk

      - name: Patch arm64-v8a
        run: |
          ./build.sh arm64-v8a
          mv patched_signed.apk waterfox-${{ env.VERSION }}-arm64-v8a-AMOLED.apk

      - name: Generate debug keystore if missing
        run: |
          if [ ! -f debug.keystore ]; then
            keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android \
              -dname "CN=Android Debug,O=Android,C=US" -keyalg RSA -keysize 2048 -validity 10000
          fi

      - name: Sign APKs
        run: |
          apksigner sign --ks debug.keystore --ks-pass pass:android waterfox-${{ env.VERSION }}-armeabi-v7a-AMOLED.apk
          apksigner sign --ks debug.keystore --ks-pass pass:android waterfox-${{ env.VERSION }}-arm64-v8a-AMOLED.apk

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: amoled-${{ env.VERSION }}
          name: AMOLED Waterfox ${{ env.VERSION }}
          body: |
            ✅ Auto-generated AMOLED-patched Waterfox Android builds.
          files: |
            waterfox-${{ env.VERSION }}-armeabi-v7a-AMOLED.apk
            waterfox-${{ env.VERSION }}-arm64-v8a-AMOLED.apk
